version: "3"

services:
  samba:
    container_name: samba
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    environment:
      TZ: "Europe/Madrid"
      SHARE: "${SHARE_NAME};/${SHARE_NAME};yes;yes;yes;;;;${SHARE_NAME}"
      NMBD: "true"
      USERID: $USER_ID
      GROUPID: $GROUP_ID
    volumes:
      - ${SHARE_PATH}:/${SHARE_NAME}
    restart: unless-stopped
